### ISSUE TITLE
A little installation help?

### ISSUE THREAD

**Issue by findborg** [cjwiseman11/Feedify#12]
I am trying to install in localhost/feeds on my test machine.  I was wondering if you would not mind giving me some simple install instructions.  I have done some basic digging but would like to get it up and running before I mess something up.

**Comment by cjwiseman11** [comment]
I've been meaning to update the README to include full installation instructions so apologies.

Firstly you'll need to set a MySQL database. It is a bit of a mess currently as I was learning PHP/MySQL from scratch when I started this and have only tidied up half of it. Here are the tables required:

## channelfeed-links: linking channels and feeds together by ID
CREATE TABLE `channelfeed-links` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `channelid` int(11) NOT NULL,
 `newsfeedid` int(11) NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=88 DEFAULT CHARSET=latin1

## channels: table containing channel names and IDs (feedids and postids are redundant now so you could skip these out)
CREATE TABLE `channels` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `channame` text NOT NULL,
 `feedids` int(11) NOT NULL,
 `postids` int(11) NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=latin1

## keeploggedin: stores user cookies for remember me functionality
CREATE TABLE `keeploggedin` (
 `memberid` int(11) NOT NULL,
 `token` varchar(34) NOT NULL,
 UNIQUE KEY `token` (`token`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1

## memberchannels: store channel IDs for each member
CREATE TABLE `memberchannels` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `chanid` int(11) NOT NULL,
 `memberid` int(11) NOT NULL,
 `hidden` tinyint(1) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=latin1

## memberfeeds: linking members to feeds
CREATE TABLE `memberfeeds` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `memberid` int(11) NOT NULL,
 `feedid` int(11) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=latin1

## members: store members user/pass/email
CREATE TABLE `members` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `username` text NOT NULL,
 `password` varchar(34) NOT NULL,
 `email` text NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=latin1

## newsfeeds: stores all the RSS links
CREATE TABLE `newsfeeds` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `rsslink` text NOT NULL,
 `rssSrcSite` text NOT NULL,
 `channels` text NOT NULL,
 `feedtitle` text NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=148 DEFAULT CHARSET=latin1

## posts: stores each post from all feeds/rss links
CREATE TABLE `posts` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `title` text NOT NULL,
 `link` text NOT NULL,
 `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `sticky` text NOT NULL,
 `vote` int(11) NOT NULL,
 `metDesc` text NOT NULL,
 `type` text NOT NULL,
 `feedsrc` text NOT NULL,
 `pubDate` text NOT NULL,
 `imgSrc` text NOT NULL,
 `channels` text NOT NULL,
 `newsfeedid` int(11) NOT NULL,
 `archived` tinyint(1) NOT NULL,
 `redditlink` text NOT NULL,
 PRIMARY KEY (`id`),
 KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=46828 DEFAULT CHARSET=latin1

## savedposts: to store members saved posts
CREATE TABLE `savedposts` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `memberid` int(11) NOT NULL,
 `postid` int(11) NOT NULL,
 `timesaved` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=74 DEFAULT CHARSET=latin1

Once the tables are in, and you have cloned/copied the files to your localhost it should be up and running.

You will need to set up a cron job to run the _rootfiles. For example:

## autoChanSubmit.php
This hits all the RSS links found in newsfeeds and gets the latest post if it is unique/new and saves it to posts. Posts then appear in the feed.

You will also need to put a config.ini file in your root (outside of feedify/public_html) with database access info.

Hope this all helps. Feel free to ask any other questions

**Comment by findborg** [comment]
I give it a go and let you know how it is working
